# Copyright (c) 2026 Steve Taranto staranto@gmail.com.
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean dist folder
        run: |
          rm -rf dist

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
          gpg --list-secret-keys

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_PAT }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-outputs
          path: dist/
          retention-days: 5

      - name: Make new release in tap
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo tfctl/homebrew-tfctl \
            --title "${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }} for Homebrew tap." \
            --prerelease \
            --latest
        env:
          GH_TOKEN: ${{ secrets.GH_GORELEASER_PAT }}

      - name: Copy Brew artifacts to tap
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          # Upload archives
          gh release upload "${{ github.ref_name }}" \
            dist/*.{tar.gz,zip,tar.xz,tgz} \
            --repo tfctl/homebrew-tfctl --clobber || true

          # Upload detached signatures
          gh release upload "${{ github.ref_name }}" \
            dist/*.{tar.gz.sig,zip.sig,tar.xz.sig,tgz.sig} \
            --repo tfctl/homebrew-tfctl --clobber || true

          # Upload docs
          gh release upload "${{ github.ref_name }}" \
            README.md LICENSE \
            --repo tfctl/homebrew-tfctl --clobber
        env:
          GH_TOKEN: ${{ secrets.GH_GORELEASER_PAT }}
